added prop to highlight a row
FocusCookie/memory pull request #44
Opened 2021-11-10 17:50 UTC by irrelevation

2021-11-10 18:02 UTC, FocusCookie requested changes

2021-11-10 18:02 UTC, FocusCookie commented on src/components/Table/Table.jsx
> +  highlight: false,
Dein Highlight hat vom PropType Number und hier ist es auf false. evtl auf 0 setzen?

2021-11-11 07:29 UTC, irrelevation commented on src/components/Table/Table.jsx
> +  highlight: false,
Hab es einfach rausgenommen, denn undefined ist ja eh falsy.

2021-11-11 09:08 UTC, FocusCookie approved these changes

2021-11-11 09:08 UTC, merged